

{
  
  gInterpreter->Load("storedataL0.C+");
  gInterpreter->Load("graphL0.C+");

  int event , fevent, levent;
  int Nevents = 0;
  int Nclusters = 0;
  char input[10000];
  int cluster;

  cout<<"====================================================================\n";
  cout<<"This is a ROOT Macro to plot the results of the ASIC for L0 Trigger\n";
 
  cout << "Decision simulator\n";
  cout<<"====================================================================\n";

  /*cout<<"Please, enter the number of events to plot.\n";
  cout<<"Number of events: ";
  cin.get(input, 10000);
  cin.ignore();
  Nevents = atoi(input);
  cout<< Nevents <<endl;*/
  cout<<"You can plot any event generated by the L0 ASIC simulator.(Remember that the simulator generates events from 0 to Number of events - 1)" << endl;
  cout<<"Please, enter the first event you want to plot." << endl;
  cout<<"First event: ";
  cin.get(input,10000);
  cin.ignore();
  fevent = atoi(input);
  cout<<"Please, enter the last event you want to plot." << endl;
  cout<<"Last event: ";
  cin.get(input,10000);
  cin.ignore();
  levent = atoi(input);

  Nevents = levent - fevent;
  
  if (Nevents >= 0){
  
  for (event= fevent; event<= levent; event++){

    storedataL0(event);
    for (cluster = 0; cluster < 7; cluster++){
    
      graphL0(event,cluster);
    }
    
  }
  }
  
}
