{
//=========Macro generated from canvas: All Offsets/All Offsets
//=========  (Wed Apr 20 11:06:13 2016) by ROOT version5.34/32
   TCanvas *All Offsets = new TCanvas("All Offsets", "All Offsets",2,77,1000,800);
   All Offsets->Range(0,0,1,1);
   All Offsets->SetFillColor(0);
   All Offsets->SetBorderMode(0);
   All Offsets->SetBorderSize(2);
   All Offsets->SetGridx();
   All Offsets->SetGridy();
   All Offsets->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: All Offsets_1
   TPad *All Offsets_1 = new TPad("All Offsets_1", "All Offsets_1",0.01,0.51,0.99,0.99);
   All Offsets_1->Draw();
   All Offsets_1->cd();
   All Offsets_1->Range(-0.1250001,-48.12172,8.125,33.43758);
   All Offsets_1->SetFillColor(0);
   All Offsets_1->SetBorderMode(0);
   All Offsets_1->SetBorderSize(2);
   All Offsets_1->SetGridx();
   All Offsets_1->SetGridy();
   All Offsets_1->SetFrameBorderMode(0);
   All Offsets_1->SetFrameBorderMode(0);
   
   TMultiGraph *multigraph = new TMultiGraph();
   multigraph->SetName("");
   multigraph->SetTitle("Output 0");
   
   TGraphErrors *gre = new TGraphErrors(7);
   gre->SetName("Graph");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetMarkerStyle(20);
   gre->SetPoint(0,1,5);
   gre->SetPointError(0,0,0);
   gre->SetPoint(1,2,16);
   gre->SetPointError(1,0,0);
   gre->SetPoint(2,3,1);
   gre->SetPointError(2,0,0);
   gre->SetPoint(3,4,12);
   gre->SetPointError(3,0,0);
   gre->SetPoint(4,5,13);
   gre->SetPointError(4,0,0);
   gre->SetPoint(5,6,13);
   gre->SetPointError(5,0,0);
   gre->SetPoint(6,7,8);
   gre->SetPointError(6,0,0);
   
   TH1F *Graph_Graph1 = new TH1F("Graph_Graph1","Graph",100,0.4,7.6);
   Graph_Graph1->SetMinimum(0);
   Graph_Graph1->SetMaximum(17.5);
   Graph_Graph1->SetDirectory(0);
   Graph_Graph1->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   Graph_Graph1->SetLineColor(ci);
   Graph_Graph1->GetXaxis()->SetLabelFont(42);
   Graph_Graph1->GetXaxis()->SetLabelSize(0.035);
   Graph_Graph1->GetXaxis()->SetTitleSize(0.035);
   Graph_Graph1->GetXaxis()->SetTitleFont(42);
   Graph_Graph1->GetYaxis()->SetLabelFont(42);
   Graph_Graph1->GetYaxis()->SetLabelSize(0.035);
   Graph_Graph1->GetYaxis()->SetTitleSize(0.035);
   Graph_Graph1->GetYaxis()->SetTitleFont(42);
   Graph_Graph1->GetZaxis()->SetLabelFont(42);
   Graph_Graph1->GetZaxis()->SetLabelSize(0.035);
   Graph_Graph1->GetZaxis()->SetTitleSize(0.035);
   Graph_Graph1->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(Graph_Graph1);
   
   multigraph->Add(gre,"");
   
   gre = new TGraphErrors(7);
   gre->SetName("Graph");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetMarkerColor(2);
   gre->SetMarkerStyle(21);
   gre->SetPoint(0,1,-21);
   gre->SetPointError(0,0,0);
   gre->SetPoint(1,2,-14);
   gre->SetPointError(1,0,0);
   gre->SetPoint(2,3,-27);
   gre->SetPointError(2,0,0);
   gre->SetPoint(3,4,-16);
   gre->SetPointError(3,0,0);
   gre->SetPoint(4,5,-14);
   gre->SetPointError(4,0,0);
   gre->SetPoint(5,6,-15);
   gre->SetPointError(5,0,0);
   gre->SetPoint(6,7,-19);
   gre->SetPointError(6,0,0);
   
   TH1F *Graph_Graph2 = new TH1F("Graph_Graph2","Graph",100,0.4,7.6);
   Graph_Graph2->SetMinimum(-28.3);
   Graph_Graph2->SetMaximum(-12.7);
   Graph_Graph2->SetDirectory(0);
   Graph_Graph2->SetStats(0);

   ci = TColor::GetColor("#000099");
   Graph_Graph2->SetLineColor(ci);
   Graph_Graph2->GetXaxis()->SetLabelFont(42);
   Graph_Graph2->GetXaxis()->SetLabelSize(0.035);
   Graph_Graph2->GetXaxis()->SetTitleSize(0.035);
   Graph_Graph2->GetXaxis()->SetTitleFont(42);
   Graph_Graph2->GetYaxis()->SetLabelFont(42);
   Graph_Graph2->GetYaxis()->SetLabelSize(0.035);
   Graph_Graph2->GetYaxis()->SetTitleSize(0.035);
   Graph_Graph2->GetYaxis()->SetTitleFont(42);
   Graph_Graph2->GetZaxis()->SetLabelFont(42);
   Graph_Graph2->GetZaxis()->SetLabelSize(0.035);
   Graph_Graph2->GetZaxis()->SetTitleSize(0.035);
   Graph_Graph2->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(Graph_Graph2);
   
   multigraph->Add(gre,"");
   
   gre = new TGraphErrors(7);
   gre->SetName("Graph");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetMarkerColor(4);
   gre->SetMarkerStyle(22);
   gre->SetPoint(0,1,-32);
   gre->SetPointError(0,0,0);
   gre->SetPoint(1,2,-24);
   gre->SetPointError(1,0,0);
   gre->SetPoint(2,3,-37);
   gre->SetPointError(2,0,0);
   gre->SetPoint(3,4,-27);
   gre->SetPointError(3,0,0);
   gre->SetPoint(4,5,-24);
   gre->SetPointError(4,0,0);
   gre->SetPoint(5,6,-25);
   gre->SetPointError(5,0,0);
   gre->SetPoint(6,7,-30);
   gre->SetPointError(6,0,0);
   
   TH1F *Graph_Graph3 = new TH1F("Graph_Graph3","Graph",100,0.4,7.6);
   Graph_Graph3->SetMinimum(-38.3);
   Graph_Graph3->SetMaximum(-22.7);
   Graph_Graph3->SetDirectory(0);
   Graph_Graph3->SetStats(0);

   ci = TColor::GetColor("#000099");
   Graph_Graph3->SetLineColor(ci);
   Graph_Graph3->GetXaxis()->SetLabelFont(42);
   Graph_Graph3->GetXaxis()->SetLabelSize(0.035);
   Graph_Graph3->GetXaxis()->SetTitleSize(0.035);
   Graph_Graph3->GetXaxis()->SetTitleFont(42);
   Graph_Graph3->GetYaxis()->SetLabelFont(42);
   Graph_Graph3->GetYaxis()->SetLabelSize(0.035);
   Graph_Graph3->GetYaxis()->SetTitleSize(0.035);
   Graph_Graph3->GetYaxis()->SetTitleFont(42);
   Graph_Graph3->GetZaxis()->SetLabelFont(42);
   Graph_Graph3->GetZaxis()->SetLabelSize(0.035);
   Graph_Graph3->GetZaxis()->SetTitleSize(0.035);
   Graph_Graph3->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(Graph_Graph3);
   
   multigraph->Add(gre,"");
   
   gre = new TGraphErrors(7);
   gre->SetName("Graph");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetMarkerColor(3);
   gre->SetMarkerStyle(23);
   gre->SetPoint(0,1,7);
   gre->SetPointError(0,0,0);
   gre->SetPoint(1,2,18);
   gre->SetPointError(1,0,0);
   gre->SetPoint(2,3,2.5);
   gre->SetPointError(2,0,0);
   gre->SetPoint(3,4,13);
   gre->SetPointError(3,0,0);
   gre->SetPoint(4,5,12.5);
   gre->SetPointError(4,0,0);
   gre->SetPoint(5,6,14);
   gre->SetPointError(5,0,0);
   gre->SetPoint(6,7,8);
   gre->SetPointError(6,0,0);
   
   TH1F *Graph_Graph4 = new TH1F("Graph_Graph4","Graph",100,0.4,7.6);
   Graph_Graph4->SetMinimum(0.95);
   Graph_Graph4->SetMaximum(19.55);
   Graph_Graph4->SetDirectory(0);
   Graph_Graph4->SetStats(0);

   ci = TColor::GetColor("#000099");
   Graph_Graph4->SetLineColor(ci);
   Graph_Graph4->GetXaxis()->SetLabelFont(42);
   Graph_Graph4->GetXaxis()->SetLabelSize(0.035);
   Graph_Graph4->GetXaxis()->SetTitleSize(0.035);
   Graph_Graph4->GetXaxis()->SetTitleFont(42);
   Graph_Graph4->GetYaxis()->SetLabelFont(42);
   Graph_Graph4->GetYaxis()->SetLabelSize(0.035);
   Graph_Graph4->GetYaxis()->SetTitleSize(0.035);
   Graph_Graph4->GetYaxis()->SetTitleFont(42);
   Graph_Graph4->GetZaxis()->SetLabelFont(42);
   Graph_Graph4->GetZaxis()->SetLabelSize(0.035);
   Graph_Graph4->GetZaxis()->SetTitleSize(0.035);
   Graph_Graph4->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(Graph_Graph4);
   
   multigraph->Add(gre,"");
   
   gre = new TGraphErrors(7);
   gre->SetName("Graph");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetMarkerStyle(24);
   gre->SetPoint(0,1,13.8);
   gre->SetPointError(0,0,5.6285);
   gre->SetPoint(1,2,18);
   gre->SetPointError(1,0,4.31586);
   gre->SetPoint(2,3,14.8);
   gre->SetPointError(2,0,6.25779);
   gre->SetPoint(3,4,14.6);
   gre->SetPointError(3,0,2.02649);
   gre->SetPoint(4,5,14.7);
   gre->SetPointError(4,0,2.44472);
   gre->SetPoint(5,6,15.2);
   gre->SetPointError(5,0,5.70614);
   gre->SetPoint(6,7,6.5);
   gre->SetPointError(6,0,3.39853);
   
   TH1F *Graph_Graph5 = new TH1F("Graph_Graph5","Graph",100,0.4,7.6);
   Graph_Graph5->SetMinimum(1.180031);
   Graph_Graph5->SetMaximum(24.2373);
   Graph_Graph5->SetDirectory(0);
   Graph_Graph5->SetStats(0);

   ci = TColor::GetColor("#000099");
   Graph_Graph5->SetLineColor(ci);
   Graph_Graph5->GetXaxis()->SetLabelFont(42);
   Graph_Graph5->GetXaxis()->SetLabelSize(0.035);
   Graph_Graph5->GetXaxis()->SetTitleSize(0.035);
   Graph_Graph5->GetXaxis()->SetTitleFont(42);
   Graph_Graph5->GetYaxis()->SetLabelFont(42);
   Graph_Graph5->GetYaxis()->SetLabelSize(0.035);
   Graph_Graph5->GetYaxis()->SetTitleSize(0.035);
   Graph_Graph5->GetYaxis()->SetTitleFont(42);
   Graph_Graph5->GetZaxis()->SetLabelFont(42);
   Graph_Graph5->GetZaxis()->SetLabelSize(0.035);
   Graph_Graph5->GetZaxis()->SetTitleSize(0.035);
   Graph_Graph5->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(Graph_Graph5);
   
   multigraph->Add(gre,"");
   
   gre = new TGraphErrors(7);
   gre->SetName("Graph");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetMarkerColor(2);
   gre->SetMarkerStyle(25);
   gre->SetPoint(0,1,-7.59999);
   gre->SetPointError(0,0,4.59565);
   gre->SetPoint(1,2,-0.2);
   gre->SetPointError(1,0,4.94907);
   gre->SetPoint(2,3,-16.6);
   gre->SetPointError(2,0,3.59258);
   gre->SetPoint(3,4,-7.4);
   gre->SetPointError(3,0,8.58914);
   gre->SetPoint(4,5,-3.6);
   gre->SetPointError(4,0,3.99833);
   gre->SetPoint(5,6,-8.00001);
   gre->SetPointError(5,0,2.42212);
   gre->SetPoint(6,7,-10.6);
   gre->SetPointError(6,0,6.12753);
   
   TH1F *Graph_Graph6 = new TH1F("Graph_Graph6","Graph",100,0.4,7.6);
   Graph_Graph6->SetMinimum(-22.68675);
   Graph_Graph6->SetMaximum(7.243235);
   Graph_Graph6->SetDirectory(0);
   Graph_Graph6->SetStats(0);

   ci = TColor::GetColor("#000099");
   Graph_Graph6->SetLineColor(ci);
   Graph_Graph6->GetXaxis()->SetLabelFont(42);
   Graph_Graph6->GetXaxis()->SetLabelSize(0.035);
   Graph_Graph6->GetXaxis()->SetTitleSize(0.035);
   Graph_Graph6->GetXaxis()->SetTitleFont(42);
   Graph_Graph6->GetYaxis()->SetLabelFont(42);
   Graph_Graph6->GetYaxis()->SetLabelSize(0.035);
   Graph_Graph6->GetYaxis()->SetTitleSize(0.035);
   Graph_Graph6->GetYaxis()->SetTitleFont(42);
   Graph_Graph6->GetZaxis()->SetLabelFont(42);
   Graph_Graph6->GetZaxis()->SetLabelSize(0.035);
   Graph_Graph6->GetZaxis()->SetTitleSize(0.035);
   Graph_Graph6->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(Graph_Graph6);
   
   multigraph->Add(gre,"");
   
   gre = new TGraphErrors(7);
   gre->SetName("Graph");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetMarkerColor(4);
   gre->SetMarkerStyle(26);
   gre->SetPoint(0,1,-23.2);
   gre->SetPointError(0,0,8.29377);
   gre->SetPoint(1,2,-12.8);
   gre->SetPointError(1,0,2.13229);
   gre->SetPoint(2,3,-29.9);
   gre->SetPointError(2,0,3.1289);
   gre->SetPoint(3,4,-14.9);
   gre->SetPointError(3,0,7.05904);
   gre->SetPoint(4,5,-20.8);
   gre->SetPointError(4,0,3.24962);
   gre->SetPoint(5,6,-20.6);
   gre->SetPointError(5,0,7.35663);
   gre->SetPoint(6,7,-23.6);
   gre->SetPointError(6,0,5.3204);
   
   TH1F *Graph_Graph7 = new TH1F("Graph_Graph7","Graph",100,0.4,7.6);
   Graph_Graph7->SetMinimum(-35.54769);
   Graph_Graph7->SetMaximum(-5.322166);
   Graph_Graph7->SetDirectory(0);
   Graph_Graph7->SetStats(0);

   ci = TColor::GetColor("#000099");
   Graph_Graph7->SetLineColor(ci);
   Graph_Graph7->GetXaxis()->SetLabelFont(42);
   Graph_Graph7->GetXaxis()->SetLabelSize(0.035);
   Graph_Graph7->GetXaxis()->SetTitleSize(0.035);
   Graph_Graph7->GetXaxis()->SetTitleFont(42);
   Graph_Graph7->GetYaxis()->SetLabelFont(42);
   Graph_Graph7->GetYaxis()->SetLabelSize(0.035);
   Graph_Graph7->GetYaxis()->SetTitleSize(0.035);
   Graph_Graph7->GetYaxis()->SetTitleFont(42);
   Graph_Graph7->GetZaxis()->SetLabelFont(42);
   Graph_Graph7->GetZaxis()->SetLabelSize(0.035);
   Graph_Graph7->GetZaxis()->SetTitleSize(0.035);
   Graph_Graph7->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(Graph_Graph7);
   
   multigraph->Add(gre,"");
   multigraph->Draw("ap1");
   multigraph->GetXaxis()->SetTitle("Channel");
   multigraph->GetXaxis()->SetLabelFont(42);
   multigraph->GetXaxis()->SetLabelSize(0.035);
   multigraph->GetXaxis()->SetTitleSize(0.035);
   multigraph->GetXaxis()->SetTitleFont(42);
   multigraph->GetYaxis()->SetTitle("Offset[mV]");
   multigraph->GetYaxis()->SetLabelFont(42);
   multigraph->GetYaxis()->SetLabelSize(0.035);
   multigraph->GetYaxis()->SetTitleSize(0.035);
   multigraph->GetYaxis()->SetTitleFont(42);
   
   TPaveText *pt = new TPaveText(0.4501243,0.9304005,0.5498757,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *text = pt->AddText("Output 0");
   pt->Draw();
   
   TLegend *leg = new TLegend(0.76,0.73,0.94,0.99,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("Graph","Analog offset, Adder A","1p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Graph","Analog offset, Adder B","1p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(2);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Graph","Analog offset, Adder C","1p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(4);
   entry->SetMarkerStyle(22);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Graph","Digital offset, Adder A","1p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(3);
   entry->SetMarkerStyle(23);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Graph","Fit offset, Adder A","1p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(24);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Graph","Fit offset, Adder B","1p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(2);
   entry->SetMarkerStyle(25);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Graph","Fit offset, Adder C","1p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(4);
   entry->SetMarkerStyle(26);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   All Offsets_1->Modified();
   All Offsets->cd();
  
// ------------>Primitives in pad: All Offsets_2
   All Offsets_2 = new TPad("All Offsets_2", "All Offsets_2",0.01,0.01,0.99,0.49);
   All Offsets_2->Draw();
   All Offsets_2->cd();
   All Offsets_2->Range(-0.1250001,-52.90626,8.125,34.19304);
   All Offsets_2->SetFillColor(0);
   All Offsets_2->SetBorderMode(0);
   All Offsets_2->SetBorderSize(2);
   All Offsets_2->SetGridx();
   All Offsets_2->SetGridy();
   All Offsets_2->SetFrameBorderMode(0);
   All Offsets_2->SetFrameBorderMode(0);
   
   multigraph = new TMultiGraph();
   multigraph->SetName("");
   multigraph->SetTitle("Output 1");
   
   gre = new TGraphErrors(7);
   gre->SetName("Graph");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetMarkerStyle(20);
   gre->SetPoint(0,1,5);
   gre->SetPointError(0,0,0);
   gre->SetPoint(1,2,16);
   gre->SetPointError(1,0,0);
   gre->SetPoint(2,3,1);
   gre->SetPointError(2,0,0);
   gre->SetPoint(3,4,12);
   gre->SetPointError(3,0,0);
   gre->SetPoint(4,5,13);
   gre->SetPointError(4,0,0);
   gre->SetPoint(5,6,13);
   gre->SetPointError(5,0,0);
   gre->SetPoint(6,7,8);
   gre->SetPointError(6,0,0);
   
   TH1F *Graph_Graph_Graph18 = new TH1F("Graph_Graph_Graph18","Graph",100,0.4,7.6);
   Graph_Graph_Graph18->SetMinimum(0);
   Graph_Graph_Graph18->SetMaximum(17.5);
   Graph_Graph_Graph18->SetDirectory(0);
   Graph_Graph_Graph18->SetStats(0);

   ci = TColor::GetColor("#000099");
   Graph_Graph_Graph18->SetLineColor(ci);
   Graph_Graph_Graph18->GetXaxis()->SetLabelFont(42);
   Graph_Graph_Graph18->GetXaxis()->SetLabelSize(0.035);
   Graph_Graph_Graph18->GetXaxis()->SetTitleSize(0.035);
   Graph_Graph_Graph18->GetXaxis()->SetTitleFont(42);
   Graph_Graph_Graph18->GetYaxis()->SetLabelFont(42);
   Graph_Graph_Graph18->GetYaxis()->SetLabelSize(0.035);
   Graph_Graph_Graph18->GetYaxis()->SetTitleSize(0.035);
   Graph_Graph_Graph18->GetYaxis()->SetTitleFont(42);
   Graph_Graph_Graph18->GetZaxis()->SetLabelFont(42);
   Graph_Graph_Graph18->GetZaxis()->SetLabelSize(0.035);
   Graph_Graph_Graph18->GetZaxis()->SetTitleSize(0.035);
   Graph_Graph_Graph18->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(Graph_Graph_Graph18);
   
   multigraph->Add(gre,"");
   
   gre = new TGraphErrors(7);
   gre->SetName("Graph");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetMarkerColor(2);
   gre->SetMarkerStyle(21);
   gre->SetPoint(0,1,-21);
   gre->SetPointError(0,0,0);
   gre->SetPoint(1,2,-14);
   gre->SetPointError(1,0,0);
   gre->SetPoint(2,3,-27);
   gre->SetPointError(2,0,0);
   gre->SetPoint(3,4,-16);
   gre->SetPointError(3,0,0);
   gre->SetPoint(4,5,-14);
   gre->SetPointError(4,0,0);
   gre->SetPoint(5,6,-15);
   gre->SetPointError(5,0,0);
   gre->SetPoint(6,7,-19);
   gre->SetPointError(6,0,0);
   
   TH1F *Graph_Graph_Graph29 = new TH1F("Graph_Graph_Graph29","Graph",100,0.4,7.6);
   Graph_Graph_Graph29->SetMinimum(-28.3);
   Graph_Graph_Graph29->SetMaximum(-12.7);
   Graph_Graph_Graph29->SetDirectory(0);
   Graph_Graph_Graph29->SetStats(0);

   ci = TColor::GetColor("#000099");
   Graph_Graph_Graph29->SetLineColor(ci);
   Graph_Graph_Graph29->GetXaxis()->SetLabelFont(42);
   Graph_Graph_Graph29->GetXaxis()->SetLabelSize(0.035);
   Graph_Graph_Graph29->GetXaxis()->SetTitleSize(0.035);
   Graph_Graph_Graph29->GetXaxis()->SetTitleFont(42);
   Graph_Graph_Graph29->GetYaxis()->SetLabelFont(42);
   Graph_Graph_Graph29->GetYaxis()->SetLabelSize(0.035);
   Graph_Graph_Graph29->GetYaxis()->SetTitleSize(0.035);
   Graph_Graph_Graph29->GetYaxis()->SetTitleFont(42);
   Graph_Graph_Graph29->GetZaxis()->SetLabelFont(42);
   Graph_Graph_Graph29->GetZaxis()->SetLabelSize(0.035);
   Graph_Graph_Graph29->GetZaxis()->SetTitleSize(0.035);
   Graph_Graph_Graph29->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(Graph_Graph_Graph29);
   
   multigraph->Add(gre,"");
   
   gre = new TGraphErrors(7);
   gre->SetName("Graph");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetMarkerColor(4);
   gre->SetMarkerStyle(22);
   gre->SetPoint(0,1,-32);
   gre->SetPointError(0,0,0);
   gre->SetPoint(1,2,-24);
   gre->SetPointError(1,0,0);
   gre->SetPoint(2,3,-37);
   gre->SetPointError(2,0,0);
   gre->SetPoint(3,4,-27);
   gre->SetPointError(3,0,0);
   gre->SetPoint(4,5,-24);
   gre->SetPointError(4,0,0);
   gre->SetPoint(5,6,-25);
   gre->SetPointError(5,0,0);
   gre->SetPoint(6,7,-30);
   gre->SetPointError(6,0,0);
   
   TH1F *Graph_Graph_Graph310 = new TH1F("Graph_Graph_Graph310","Graph",100,0.4,7.6);
   Graph_Graph_Graph310->SetMinimum(-38.3);
   Graph_Graph_Graph310->SetMaximum(-22.7);
   Graph_Graph_Graph310->SetDirectory(0);
   Graph_Graph_Graph310->SetStats(0);

   ci = TColor::GetColor("#000099");
   Graph_Graph_Graph310->SetLineColor(ci);
   Graph_Graph_Graph310->GetXaxis()->SetLabelFont(42);
   Graph_Graph_Graph310->GetXaxis()->SetLabelSize(0.035);
   Graph_Graph_Graph310->GetXaxis()->SetTitleSize(0.035);
   Graph_Graph_Graph310->GetXaxis()->SetTitleFont(42);
   Graph_Graph_Graph310->GetYaxis()->SetLabelFont(42);
   Graph_Graph_Graph310->GetYaxis()->SetLabelSize(0.035);
   Graph_Graph_Graph310->GetYaxis()->SetTitleSize(0.035);
   Graph_Graph_Graph310->GetYaxis()->SetTitleFont(42);
   Graph_Graph_Graph310->GetZaxis()->SetLabelFont(42);
   Graph_Graph_Graph310->GetZaxis()->SetLabelSize(0.035);
   Graph_Graph_Graph310->GetZaxis()->SetTitleSize(0.035);
   Graph_Graph_Graph310->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(Graph_Graph_Graph310);
   
   multigraph->Add(gre,"");
   
   gre = new TGraphErrors(7);
   gre->SetName("Graph");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetMarkerColor(3);
   gre->SetMarkerStyle(23);
   gre->SetPoint(0,1,9.5);
   gre->SetPointError(0,0,0);
   gre->SetPoint(1,2,16);
   gre->SetPointError(1,0,0);
   gre->SetPoint(2,3,2.5);
   gre->SetPointError(2,0,0);
   gre->SetPoint(3,4,12.5);
   gre->SetPointError(3,0,0);
   gre->SetPoint(4,5,12.5);
   gre->SetPointError(4,0,0);
   gre->SetPoint(5,6,14);
   gre->SetPointError(5,0,0);
   gre->SetPoint(6,7,7.5);
   gre->SetPointError(6,0,0);
   
   TH1F *Graph_Graph11 = new TH1F("Graph_Graph11","Graph",100,0.4,7.6);
   Graph_Graph11->SetMinimum(1.15);
   Graph_Graph11->SetMaximum(17.35);
   Graph_Graph11->SetDirectory(0);
   Graph_Graph11->SetStats(0);

   ci = TColor::GetColor("#000099");
   Graph_Graph11->SetLineColor(ci);
   Graph_Graph11->GetXaxis()->SetLabelFont(42);
   Graph_Graph11->GetXaxis()->SetLabelSize(0.035);
   Graph_Graph11->GetXaxis()->SetTitleSize(0.035);
   Graph_Graph11->GetXaxis()->SetTitleFont(42);
   Graph_Graph11->GetYaxis()->SetLabelFont(42);
   Graph_Graph11->GetYaxis()->SetLabelSize(0.035);
   Graph_Graph11->GetYaxis()->SetTitleSize(0.035);
   Graph_Graph11->GetYaxis()->SetTitleFont(42);
   Graph_Graph11->GetZaxis()->SetLabelFont(42);
   Graph_Graph11->GetZaxis()->SetLabelSize(0.035);
   Graph_Graph11->GetZaxis()->SetTitleSize(0.035);
   Graph_Graph11->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(Graph_Graph11);
   
   multigraph->Add(gre,"");
   
   gre = new TGraphErrors(7);
   gre->SetName("Graph");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetMarkerStyle(24);
   gre->SetPoint(0,1,13.8);
   gre->SetPointError(0,0,5.6285);
   gre->SetPoint(1,2,18);
   gre->SetPointError(1,0,4.31586);
   gre->SetPoint(2,3,14.8);
   gre->SetPointError(2,0,6.25779);
   gre->SetPoint(3,4,14.6);
   gre->SetPointError(3,0,2.02649);
   gre->SetPoint(4,5,14.7);
   gre->SetPointError(4,0,2.44472);
   gre->SetPoint(5,6,15.2);
   gre->SetPointError(5,0,5.70614);
   gre->SetPoint(6,7,6.5);
   gre->SetPointError(6,0,3.39853);
   
   TH1F *Graph_Graph_Graph512 = new TH1F("Graph_Graph_Graph512","Graph",100,0.4,7.6);
   Graph_Graph_Graph512->SetMinimum(1.180031);
   Graph_Graph_Graph512->SetMaximum(24.2373);
   Graph_Graph_Graph512->SetDirectory(0);
   Graph_Graph_Graph512->SetStats(0);

   ci = TColor::GetColor("#000099");
   Graph_Graph_Graph512->SetLineColor(ci);
   Graph_Graph_Graph512->GetXaxis()->SetLabelFont(42);
   Graph_Graph_Graph512->GetXaxis()->SetLabelSize(0.035);
   Graph_Graph_Graph512->GetXaxis()->SetTitleSize(0.035);
   Graph_Graph_Graph512->GetXaxis()->SetTitleFont(42);
   Graph_Graph_Graph512->GetYaxis()->SetLabelFont(42);
   Graph_Graph_Graph512->GetYaxis()->SetLabelSize(0.035);
   Graph_Graph_Graph512->GetYaxis()->SetTitleSize(0.035);
   Graph_Graph_Graph512->GetYaxis()->SetTitleFont(42);
   Graph_Graph_Graph512->GetZaxis()->SetLabelFont(42);
   Graph_Graph_Graph512->GetZaxis()->SetLabelSize(0.035);
   Graph_Graph_Graph512->GetZaxis()->SetTitleSize(0.035);
   Graph_Graph_Graph512->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(Graph_Graph_Graph512);
   
   multigraph->Add(gre,"");
   
   gre = new TGraphErrors(7);
   gre->SetName("Graph");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetMarkerColor(2);
   gre->SetMarkerStyle(25);
   gre->SetPoint(0,1,-21.7);
   gre->SetPointError(0,0,3.22129);
   gre->SetPoint(1,2,-9.6);
   gre->SetPointError(1,0,1.87617);
   gre->SetPoint(2,3,-25.4);
   gre->SetPointError(2,0,7.17496);
   gre->SetPoint(3,4,-10.4);
   gre->SetPointError(3,0,4.51516);
   gre->SetPoint(4,5,-3);
   gre->SetPointError(4,0,2.42212);
   gre->SetPoint(5,6,-1.00001);
   gre->SetPointError(5,0,3.3823);
   gre->SetPoint(6,7,-10.7);
   gre->SetPointError(6,0,3.84404);
   
   TH1F *Graph_Graph13 = new TH1F("Graph_Graph13","Graph",100,0.4,7.6);
   Graph_Graph13->SetMinimum(-36.07068);
   Graph_Graph13->SetMaximum(5.878015);
   Graph_Graph13->SetDirectory(0);
   Graph_Graph13->SetStats(0);

   ci = TColor::GetColor("#000099");
   Graph_Graph13->SetLineColor(ci);
   Graph_Graph13->GetXaxis()->SetLabelFont(42);
   Graph_Graph13->GetXaxis()->SetLabelSize(0.035);
   Graph_Graph13->GetXaxis()->SetTitleSize(0.035);
   Graph_Graph13->GetXaxis()->SetTitleFont(42);
   Graph_Graph13->GetYaxis()->SetLabelFont(42);
   Graph_Graph13->GetYaxis()->SetLabelSize(0.035);
   Graph_Graph13->GetYaxis()->SetTitleSize(0.035);
   Graph_Graph13->GetYaxis()->SetTitleFont(42);
   Graph_Graph13->GetZaxis()->SetLabelFont(42);
   Graph_Graph13->GetZaxis()->SetLabelSize(0.035);
   Graph_Graph13->GetZaxis()->SetTitleSize(0.035);
   Graph_Graph13->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(Graph_Graph13);
   
   multigraph->Add(gre,"");
   
   gre = new TGraphErrors(7);
   gre->SetName("Graph");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetMarkerColor(4);
   gre->SetMarkerStyle(26);
   gre->SetPoint(0,1,-28.2);
   gre->SetPointError(0,0,3.06377);
   gre->SetPoint(1,2,-20.5);
   gre->SetPointError(1,0,1.56738);
   gre->SetPoint(2,3,-36.2);
   gre->SetPointError(2,0,4.82908);
   gre->SetPoint(3,4,-16.5);
   gre->SetPointError(3,0,6.65257);
   gre->SetPoint(4,5,-17.7);
   gre->SetPointError(4,0,4.76411);
   gre->SetPoint(5,6,-15.9);
   gre->SetPointError(5,0,5.57285);
   gre->SetPoint(6,7,-27);
   gre->SetPointError(6,0,5.0372);
   
   TH1F *Graph_Graph14 = new TH1F("Graph_Graph14","Graph",100,0.4,7.6);
   Graph_Graph14->SetMinimum(-44.14725);
   Graph_Graph14->SetMaximum(-6.729265);
   Graph_Graph14->SetDirectory(0);
   Graph_Graph14->SetStats(0);

   ci = TColor::GetColor("#000099");
   Graph_Graph14->SetLineColor(ci);
   Graph_Graph14->GetXaxis()->SetLabelFont(42);
   Graph_Graph14->GetXaxis()->SetLabelSize(0.035);
   Graph_Graph14->GetXaxis()->SetTitleSize(0.035);
   Graph_Graph14->GetXaxis()->SetTitleFont(42);
   Graph_Graph14->GetYaxis()->SetLabelFont(42);
   Graph_Graph14->GetYaxis()->SetLabelSize(0.035);
   Graph_Graph14->GetYaxis()->SetTitleSize(0.035);
   Graph_Graph14->GetYaxis()->SetTitleFont(42);
   Graph_Graph14->GetZaxis()->SetLabelFont(42);
   Graph_Graph14->GetZaxis()->SetLabelSize(0.035);
   Graph_Graph14->GetZaxis()->SetTitleSize(0.035);
   Graph_Graph14->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(Graph_Graph14);
   
   multigraph->Add(gre,"");
   multigraph->Draw("ap1");
   multigraph->GetXaxis()->SetTitle("Channel");
   multigraph->GetXaxis()->SetLabelFont(42);
   multigraph->GetXaxis()->SetLabelSize(0.035);
   multigraph->GetXaxis()->SetTitleSize(0.035);
   multigraph->GetXaxis()->SetTitleFont(42);
   multigraph->GetYaxis()->SetTitle("Offset[mV]");
   multigraph->GetYaxis()->SetLabelFont(42);
   multigraph->GetYaxis()->SetLabelSize(0.035);
   multigraph->GetYaxis()->SetTitleSize(0.035);
   multigraph->GetYaxis()->SetTitleFont(42);
   
   pt = new TPaveText(0.451658,0.9304005,0.548342,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   text = pt->AddText("Output 1");
   pt->Draw();
   
   leg = new TLegend(0.76,0.73,0.94,0.99,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   entry=leg->AddEntry("Graph","Analog offset, Adder A","1p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Graph","Analog offset, Adder B","1p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(2);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Graph","Analog offset, Adder C","1p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(4);
   entry->SetMarkerStyle(22);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Graph","Digital offset, Adder A","1p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(3);
   entry->SetMarkerStyle(23);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Graph","Fit offset, Adder A","1p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(24);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Graph","Fit offset, Adder B","1p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(2);
   entry->SetMarkerStyle(25);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Graph","Fit offset, Adder C","1p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(4);
   entry->SetMarkerStyle(26);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   All Offsets_2->Modified();
   All Offsets->cd();
   All Offsets->Modified();
   All Offsets->cd();
   All Offsets->SetSelected(All Offsets);
}
