{
//=========Macro generated from canvas: Fit Offset/Fit Offset
//=========  (Wed Apr 20 08:41:50 2016) by ROOT version5.34/32
   TCanvas *Fit Offset = new TCanvas("Fit Offset", "Fit Offset",2,77,1000,800);
   Fit Offset->Range(0,0,1,1);
   Fit Offset->SetFillColor(0);
   Fit Offset->SetBorderMode(0);
   Fit Offset->SetBorderSize(2);
   Fit Offset->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: Fit Offset_1
   TPad *Fit Offset_1 = new TPad("Fit Offset_1", "Fit Offset_1",0.01,0.51,0.99,0.99);
   Fit Offset_1->Draw();
   Fit Offset_1->cd();
   Fit Offset_1->Range(-0.1250001,-43.40604,8.125,32.693);
   Fit Offset_1->SetFillColor(0);
   Fit Offset_1->SetBorderMode(0);
   Fit Offset_1->SetBorderSize(2);
   Fit Offset_1->SetFrameBorderMode(0);
   Fit Offset_1->SetFrameBorderMode(0);
   
   TMultiGraph *multigraph = new TMultiGraph();
   multigraph->SetName("");
   multigraph->SetTitle("");
   
   TGraphErrors *gre = new TGraphErrors(7);
   gre->SetName("Graph");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetMarkerStyle(21);
   gre->SetPoint(0,1,13.8);
   gre->SetPointError(0,0,5.6285);
   gre->SetPoint(1,2,18);
   gre->SetPointError(1,0,4.31586);
   gre->SetPoint(2,3,14.8);
   gre->SetPointError(2,0,6.25779);
   gre->SetPoint(3,4,14.6);
   gre->SetPointError(3,0,2.02649);
   gre->SetPoint(4,5,14.7);
   gre->SetPointError(4,0,2.44472);
   gre->SetPoint(5,6,15.2);
   gre->SetPointError(5,0,5.70614);
   gre->SetPoint(6,7,6.5);
   gre->SetPointError(6,0,3.39853);
   
   TH1F *Graph_Graph1 = new TH1F("Graph_Graph1","Graph",100,0.4,7.6);
   Graph_Graph1->SetMinimum(1.180031);
   Graph_Graph1->SetMaximum(24.2373);
   Graph_Graph1->SetDirectory(0);
   Graph_Graph1->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   Graph_Graph1->SetLineColor(ci);
   Graph_Graph1->GetXaxis()->SetLabelFont(42);
   Graph_Graph1->GetXaxis()->SetLabelSize(0.035);
   Graph_Graph1->GetXaxis()->SetTitleSize(0.035);
   Graph_Graph1->GetXaxis()->SetTitleFont(42);
   Graph_Graph1->GetYaxis()->SetLabelFont(42);
   Graph_Graph1->GetYaxis()->SetLabelSize(0.035);
   Graph_Graph1->GetYaxis()->SetTitleSize(0.035);
   Graph_Graph1->GetYaxis()->SetTitleFont(42);
   Graph_Graph1->GetZaxis()->SetLabelFont(42);
   Graph_Graph1->GetZaxis()->SetLabelSize(0.035);
   Graph_Graph1->GetZaxis()->SetTitleSize(0.035);
   Graph_Graph1->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(Graph_Graph1);
   
   multigraph->Add(gre,"");
   
   gre = new TGraphErrors(7);
   gre->SetName("Graph");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetMarkerColor(2);
   gre->SetMarkerStyle(20);
   gre->SetPoint(0,1,-7.59999);
   gre->SetPointError(0,0,4.59565);
   gre->SetPoint(1,2,-0.2);
   gre->SetPointError(1,0,4.94907);
   gre->SetPoint(2,3,-16.6);
   gre->SetPointError(2,0,3.59258);
   gre->SetPoint(3,4,-7.4);
   gre->SetPointError(3,0,8.58914);
   gre->SetPoint(4,5,-3.6);
   gre->SetPointError(4,0,3.99833);
   gre->SetPoint(5,6,-8.00001);
   gre->SetPointError(5,0,2.42212);
   gre->SetPoint(6,7,-10.6);
   gre->SetPointError(6,0,6.12753);
   
   TH1F *Graph_Graph2 = new TH1F("Graph_Graph2","Graph",100,0.4,7.6);
   Graph_Graph2->SetMinimum(-22.68675);
   Graph_Graph2->SetMaximum(7.243235);
   Graph_Graph2->SetDirectory(0);
   Graph_Graph2->SetStats(0);

   ci = TColor::GetColor("#000099");
   Graph_Graph2->SetLineColor(ci);
   Graph_Graph2->GetXaxis()->SetLabelFont(42);
   Graph_Graph2->GetXaxis()->SetLabelSize(0.035);
   Graph_Graph2->GetXaxis()->SetTitleSize(0.035);
   Graph_Graph2->GetXaxis()->SetTitleFont(42);
   Graph_Graph2->GetYaxis()->SetLabelFont(42);
   Graph_Graph2->GetYaxis()->SetLabelSize(0.035);
   Graph_Graph2->GetYaxis()->SetTitleSize(0.035);
   Graph_Graph2->GetYaxis()->SetTitleFont(42);
   Graph_Graph2->GetZaxis()->SetLabelFont(42);
   Graph_Graph2->GetZaxis()->SetLabelSize(0.035);
   Graph_Graph2->GetZaxis()->SetTitleSize(0.035);
   Graph_Graph2->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(Graph_Graph2);
   
   multigraph->Add(gre,"");
   
   gre = new TGraphErrors(7);
   gre->SetName("Graph");
   gre->SetTitle("Discriminator 0");
   gre->SetFillColor(1);
   gre->SetMarkerColor(4);
   gre->SetMarkerStyle(22);
   gre->SetPoint(0,1,-23.2);
   gre->SetPointError(0,0,8.29377);
   gre->SetPoint(1,2,-12.8);
   gre->SetPointError(1,0,2.13229);
   gre->SetPoint(2,3,-29.9);
   gre->SetPointError(2,0,3.1289);
   gre->SetPoint(3,4,-14.9);
   gre->SetPointError(3,0,7.05904);
   gre->SetPoint(4,5,-20.8);
   gre->SetPointError(4,0,3.24962);
   gre->SetPoint(5,6,-20.6);
   gre->SetPointError(5,0,7.35663);
   gre->SetPoint(6,7,-23.6);
   gre->SetPointError(6,0,5.3204);
   
   TH1F *Graph_Graph3 = new TH1F("Graph_Graph3","Discriminator 0",100,0.4,7.6);
   Graph_Graph3->SetMinimum(-35.54769);
   Graph_Graph3->SetMaximum(-5.322166);
   Graph_Graph3->SetDirectory(0);
   Graph_Graph3->SetStats(0);

   ci = TColor::GetColor("#000099");
   Graph_Graph3->SetLineColor(ci);
   Graph_Graph3->GetXaxis()->SetLabelFont(42);
   Graph_Graph3->GetXaxis()->SetLabelSize(0.035);
   Graph_Graph3->GetXaxis()->SetTitleSize(0.035);
   Graph_Graph3->GetXaxis()->SetTitleFont(42);
   Graph_Graph3->GetYaxis()->SetLabelFont(42);
   Graph_Graph3->GetYaxis()->SetLabelSize(0.035);
   Graph_Graph3->GetYaxis()->SetTitleSize(0.035);
   Graph_Graph3->GetYaxis()->SetTitleFont(42);
   Graph_Graph3->GetZaxis()->SetLabelFont(42);
   Graph_Graph3->GetZaxis()->SetLabelSize(0.035);
   Graph_Graph3->GetZaxis()->SetTitleSize(0.035);
   Graph_Graph3->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(Graph_Graph3);
   
   multigraph->Add(gre,"");
   multigraph->Draw("ap1");
   multigraph->GetXaxis()->SetTitle("Channel");
   multigraph->GetXaxis()->SetLabelFont(42);
   multigraph->GetXaxis()->SetLabelSize(0.035);
   multigraph->GetXaxis()->SetTitleSize(0.035);
   multigraph->GetXaxis()->SetTitleFont(42);
   multigraph->GetYaxis()->SetTitle("Offset[mV]");
   multigraph->GetYaxis()->SetLabelFont(42);
   multigraph->GetYaxis()->SetLabelSize(0.035);
   multigraph->GetYaxis()->SetTitleSize(0.035);
   multigraph->GetYaxis()->SetTitleFont(42);
   
   TLegend *leg = new TLegend(0.77,0.79,0.97,0.99,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("Graph","Adder A","1p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Graph","Adder B","1p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(2);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Graph","Adder C","1p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(4);
   entry->SetMarkerStyle(22);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Fit Offset_1->Modified();
   Fit Offset->cd();
  
// ------------>Primitives in pad: Fit Offset_2
   Fit Offset_2 = new TPad("Fit Offset_2", "Fit Offset_2",0.01,0.01,0.99,0.49);
   Fit Offset_2->Draw();
   Fit Offset_2->cd();
   Fit Offset_2->Range(-0.1250001,-54.40774,8.125,43.70245);
   Fit Offset_2->SetFillColor(0);
   Fit Offset_2->SetBorderMode(0);
   Fit Offset_2->SetBorderSize(2);
   Fit Offset_2->SetFrameBorderMode(0);
   Fit Offset_2->SetFrameBorderMode(0);
   
   multigraph = new TMultiGraph();
   multigraph->SetName("");
   multigraph->SetTitle("Discriminator 1");
   
   gre = new TGraphErrors(7);
   gre->SetName("Graph");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetMarkerStyle(21);
   gre->SetPoint(0,1,11.8);
   gre->SetPointError(0,0,2.76163);
   gre->SetPoint(1,2,22.5);
   gre->SetPointError(1,0,3.54637);
   gre->SetPoint(2,3,6);
   gre->SetPointError(2,0,4.24735);
   gre->SetPoint(3,4,21.2);
   gre->SetPointError(3,0,7.99667);
   gre->SetPoint(4,5,25.2);
   gre->SetPointError(4,0,5.12379);
   gre->SetPoint(5,6,24.1);
   gre->SetPointError(5,0,2.83372);
   gre->SetPoint(6,7,18.1);
   gre->SetPointError(6,0,5.63826);
   
   TH1F *Graph_Graph4 = new TH1F("Graph_Graph4","Graph",100,0.4,7.6);
   Graph_Graph4->SetMinimum(0);
   Graph_Graph4->SetMaximum(33.1809);
   Graph_Graph4->SetDirectory(0);
   Graph_Graph4->SetStats(0);

   ci = TColor::GetColor("#000099");
   Graph_Graph4->SetLineColor(ci);
   Graph_Graph4->GetXaxis()->SetLabelFont(42);
   Graph_Graph4->GetXaxis()->SetLabelSize(0.035);
   Graph_Graph4->GetXaxis()->SetTitleSize(0.035);
   Graph_Graph4->GetXaxis()->SetTitleFont(42);
   Graph_Graph4->GetYaxis()->SetLabelFont(42);
   Graph_Graph4->GetYaxis()->SetLabelSize(0.035);
   Graph_Graph4->GetYaxis()->SetTitleSize(0.035);
   Graph_Graph4->GetYaxis()->SetTitleFont(42);
   Graph_Graph4->GetZaxis()->SetLabelFont(42);
   Graph_Graph4->GetZaxis()->SetLabelSize(0.035);
   Graph_Graph4->GetZaxis()->SetTitleSize(0.035);
   Graph_Graph4->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(Graph_Graph4);
   
   multigraph->Add(gre,"");
   
   gre = new TGraphErrors(7);
   gre->SetName("Graph");
   gre->SetTitle("Graph");
   gre->SetFillColor(1);
   gre->SetMarkerColor(2);
   gre->SetMarkerStyle(20);
   gre->SetPoint(0,1,-21.7);
   gre->SetPointError(0,0,3.22129);
   gre->SetPoint(1,2,-9.6);
   gre->SetPointError(1,0,1.87617);
   gre->SetPoint(2,3,-25.4);
   gre->SetPointError(2,0,7.17496);
   gre->SetPoint(3,4,-10.4);
   gre->SetPointError(3,0,4.51516);
   gre->SetPoint(4,5,-3);
   gre->SetPointError(4,0,2.42212);
   gre->SetPoint(5,6,-1.00001);
   gre->SetPointError(5,0,3.3823);
   gre->SetPoint(6,7,-10.7);
   gre->SetPointError(6,0,3.84404);
   
   TH1F *Graph_Graph5 = new TH1F("Graph_Graph5","Graph",100,0.4,7.6);
   Graph_Graph5->SetMinimum(-36.07068);
   Graph_Graph5->SetMaximum(5.878015);
   Graph_Graph5->SetDirectory(0);
   Graph_Graph5->SetStats(0);

   ci = TColor::GetColor("#000099");
   Graph_Graph5->SetLineColor(ci);
   Graph_Graph5->GetXaxis()->SetLabelFont(42);
   Graph_Graph5->GetXaxis()->SetLabelSize(0.035);
   Graph_Graph5->GetXaxis()->SetTitleSize(0.035);
   Graph_Graph5->GetXaxis()->SetTitleFont(42);
   Graph_Graph5->GetYaxis()->SetLabelFont(42);
   Graph_Graph5->GetYaxis()->SetLabelSize(0.035);
   Graph_Graph5->GetYaxis()->SetTitleSize(0.035);
   Graph_Graph5->GetYaxis()->SetTitleFont(42);
   Graph_Graph5->GetZaxis()->SetLabelFont(42);
   Graph_Graph5->GetZaxis()->SetLabelSize(0.035);
   Graph_Graph5->GetZaxis()->SetTitleSize(0.035);
   Graph_Graph5->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(Graph_Graph5);
   
   multigraph->Add(gre,"");
   
   gre = new TGraphErrors(7);
   gre->SetName("Graph");
   gre->SetTitle("Discriminator 0");
   gre->SetFillColor(1);
   gre->SetMarkerColor(4);
   gre->SetMarkerStyle(22);
   gre->SetPoint(0,1,-28.2);
   gre->SetPointError(0,0,3.06377);
   gre->SetPoint(1,2,-20.5);
   gre->SetPointError(1,0,1.56738);
   gre->SetPoint(2,3,-36.2);
   gre->SetPointError(2,0,4.82908);
   gre->SetPoint(3,4,-16.5);
   gre->SetPointError(3,0,6.65257);
   gre->SetPoint(4,5,-17.7);
   gre->SetPointError(4,0,4.76411);
   gre->SetPoint(5,6,-15.9);
   gre->SetPointError(5,0,5.57285);
   gre->SetPoint(6,7,-27);
   gre->SetPointError(6,0,5.0372);
   
   TH1F *Graph_Graph6 = new TH1F("Graph_Graph6","Discriminator 0",100,0.4,7.6);
   Graph_Graph6->SetMinimum(-44.14725);
   Graph_Graph6->SetMaximum(-6.729265);
   Graph_Graph6->SetDirectory(0);
   Graph_Graph6->SetStats(0);

   ci = TColor::GetColor("#000099");
   Graph_Graph6->SetLineColor(ci);
   Graph_Graph6->GetXaxis()->SetLabelFont(42);
   Graph_Graph6->GetXaxis()->SetLabelSize(0.035);
   Graph_Graph6->GetXaxis()->SetTitleSize(0.035);
   Graph_Graph6->GetXaxis()->SetTitleFont(42);
   Graph_Graph6->GetYaxis()->SetLabelFont(42);
   Graph_Graph6->GetYaxis()->SetLabelSize(0.035);
   Graph_Graph6->GetYaxis()->SetTitleSize(0.035);
   Graph_Graph6->GetYaxis()->SetTitleFont(42);
   Graph_Graph6->GetZaxis()->SetLabelFont(42);
   Graph_Graph6->GetZaxis()->SetLabelSize(0.035);
   Graph_Graph6->GetZaxis()->SetTitleSize(0.035);
   Graph_Graph6->GetZaxis()->SetTitleFont(42);
   gre->SetHistogram(Graph_Graph6);
   
   multigraph->Add(gre,"");
   multigraph->Draw("ap1");
   multigraph->GetXaxis()->SetTitle("Channel");
   multigraph->GetXaxis()->SetLabelFont(42);
   multigraph->GetXaxis()->SetLabelSize(0.035);
   multigraph->GetXaxis()->SetTitleSize(0.035);
   multigraph->GetXaxis()->SetTitleFont(42);
   multigraph->GetYaxis()->SetTitle("Offset[mV]");
   multigraph->GetYaxis()->SetLabelFont(42);
   multigraph->GetYaxis()->SetLabelSize(0.035);
   multigraph->GetYaxis()->SetTitleSize(0.035);
   multigraph->GetYaxis()->SetTitleFont(42);
   
   leg = new TLegend(0.77,0.79,0.97,0.99,NULL,"brNDC");
   leg->SetBorderSize(1);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   entry=leg->AddEntry("Graph","Adder A","1p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Graph","Adder B","1p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(2);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("Graph","Adder C","1p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(4);
   entry->SetMarkerStyle(22);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   Fit Offset_2->Modified();
   Fit Offset->cd();
   Fit Offset->Modified();
   Fit Offset->cd();
   Fit Offset->SetSelected(Fit Offset);
}
